### ISSUE TITLE
Reuse of parts of AbstractStreamFetcher

### ISSUE THREAD

**Issue by jonas-app** [stefan-niedermann/nextcloud-commons#236]
First of all, thanks for your work in the Nextcloud area! 👏 

I currently develop a Kotlin Multiplatform application with Nextcloud integration.
On Android it uses the [SSO library](https://github.com/nextcloud/Android-SingleSignOn) for authentication.

To allow Nextcloud requests in the common code I developed a [custom Ktor client engine](https://git.fairkom.net/jonas/journal.st/-/blob/main/composeApp/src/androidMain/kotlin/st/journal/api/NextcloudEngine.kt) which wraps Nextcloud API from the SSO Library. It is currently just a draft to try things out and needs some clean up.
This works as expected and even allows me to use [Coil 3](https://coil-kt.github.io/coil/upgrading_to_coil3) as Image fetching library.

As I was trying to fetch a preview image from Nextcloud I stumbled upon the issue of not handling query parameters correctly.
Which brought me to the discovery of this library through this issue: https://github.com/nextcloud/Android-SingleSignOn/issues/266

For the time being I integrated not only the query param part but all of [AbstractStreamFetcher.kt](https://github.com/stefan-niedermann/nextcloud-commons/blob/master/sso-glide/src/main/java/it/niedermann/nextcloud/sso/glide/AbstractStreamFetcher.kt) into my Ktor engine and all workes as expected.
I can not import the sso-glide library and use this file directly as I do not want to have a dependency on Glide.

> [!IMPORTANT]
> I'm aware of the [GNU General Public License v3.0](https://github.com/stefan-niedermann/nextcloud-commons/blob/master/LICENSE) and its implications which brings me to my question:

I haven't yet decided on a license for my project but I would most certainly factor out your code into a extra module to publish it under GNU GPL 3.
As I have not really modified anything apart from also ignoring `/ocs` requests [in this place](https://git.fairkom.net/jonas/journal.st/-/blob/main/composeApp/src/androidMain/kotlin/st/journal/api/NextcloudEngine.kt?#L290), to not let them be converted to webdav urls, which allows me to still make non image requests through the engine, I thought it might be a better idea to make an abstracted module with this functionality here in the original repo and publish that as separate artifact.
This way I could use it in my code without copying it over.

Would you be open for such a contribution or willing to do it yourself?

**Comment by stefan-niedermann** [comment]
Hello @jonas-app :wave: 

I am open for a small refactoring, but I did not get what exactly you need / are proposing.
You mentioned the query parameter handling - shouldn't be a big deal to move this part to a glide agnostic util file or even module.

I will accept Pull Requests for it but i won't be able to work on it myself given I have little freetime in general.

**Comment by jonas-app** [comment]
Just to let you know, I opened a Draft Pull Request to show how I roughly imagine it.
https://github.com/stefan-niedermann/nextcloud-commons/pull/237

**Comment by stefan-niedermann** [comment]
Fixed in 1.9.0
