### ISSUE TITLE
Fallback to `WebDAV`

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-commons#51]
# Motivation

As a user i want to be able to fetch an image with by a path to the file in my Nextcloud user folder like `/foo/bar.png`.

## Current behavior

Given the above mentioned URL gets passed into Glide as target URL
then the `sso-glide` module should try to resolve and extract
- Share IDs → rewrite to `download` path of the shared file
- File IDs → rewrite to `preview` path of the file
- As a fallback, we just try to call the given URL and hope for the best. Tthis will work for example for fetching avatars, but not in this scenario. :x: 

## Expected behavior

Given the above mentioned URL gets passed into Glide as target URL
then the `sso-glide` module should try to resolve and extract
- Share IDs → rewrite to `download` path of the shared file
- File IDs → rewrite to `preview` path of the file
- paths starting with `/index.php/...` or `/remote.php/...` → should not be touched or modified as they can belong to avatars or app specific image resources
- As a fallback, we should try to rewrite the path of the URL to a `WebDAV` URL, like `/foo/bar.png` → rewrite to `/remote.php/webdav/foo/bar.png`. :heavy_check_mark:

**Comment by scharmach** [comment]
I didn't want to respond in a closed issue, so I'm just leaving it here: Thanks for investigating in the first place and for putting time into this! 👍

**Comment by stefan-niedermann** [comment]
Fixed in nextcloud-commons `1.4.0`. This will be featured in Notes `v3.4.11` and Deck `1.19.0`.

Drawback: spaces need to be escaped by the user in order to make it work, for example `/images/foo bar.png` → `/images/foo%20bar.png`.

This is not a restriction of nextcloud-commons, but of the commonmark Markdown specification, as a not encoded URL is per definition no valid markdown.
